export const settings = {
  wordpressLink : '/wordpress/', // Leave only '/' for production and /wordpress/ for development
  domain : 'https://yourdomain.com',
  title: 'domain title',
  mainphoto : 'image.jpg',
  mainphotoAlt: 'main image alt',
  analytics : 'UA-XXXXXXX',
  email : 'contact@yourdomain.com',
  cookiePolicySite : 'cookie-policy',
  cooperationSite : 'cooperation',
  babyPostCategory : 137,
  winterPostCategory : 18,
  autumnPostCategory : 139,
  summerPostCategory : 141,
  lifestylePostCategory : 140,
  adSenseClient: 'ca-pub-xxx',
  adSenseSlot: '111111',
  facebookLink: 'https://facebook.com/yoursite',
  instagramLink: 'https://www.instagram.com/yoursite/',
}
