export const settings = {
  wordpressLink : '/wordpress/',
  domain : 'https://aktywnepodroze.pl',
  title: 'aktywne podróże',
  mainphoto : 'https://aktywnepodroze.pl/wp-content/uploads/2018/09/cropped-IMAG4159_1.jpg',
  mainphotoAlt: 'widok na morze',
  analytics : 'UA-XXXXXXX',
  email : 'kontakt@aktywnepodroze.pl',
  cookiePolicySite : 'polityka-plikow-cookies',
  cooperationSite : 'wspolpraca',
  babyPostCategory : 137,
  winterPostCategory : 18,
  autumnPostCategory : 139,
  summerPostCategory : 141,
  lifestylePostCategory : 140,
  adSenseClient: 'ca-pub-xxx',
  adSenseSlot: '111111',
  facebookLink: 'https://facebook.com/aktywnepodroze',
  instagramLink: 'https://www.instagram.com/aktywnepodroze.pl/',
}
